-- DROP TABLE T_PR_QT_H


CREATE TABLE [dbo].[T_PR_QT_H](
    [I_QT_NO]           NVARCHAR(20) NOT NULL,   -- Quotation No (PK)
    [I_QT_MTH]          DATE NULL,
    [I_METAL_PRICE]     NVARCHAR(7) NULL,
    [I_CSCODE]          NVARCHAR(10) NOT NULL,
    [I_PO_MONTH]        DATE NULL,
    [I_EXG_MONTH]       DATE NULL,
    [I_EXG_RATE]        NUMERIC(14,8) NULL,
    [I_CURRENCY]        NVARCHAR(50) NULL,
    [I_REM1]            NVARCHAR(50) NULL,
    [I_EXG_RATE_TYPE]   NVARCHAR(1) NULL,
    [I_TYPE]            NVARCHAR(1) NULL,

    [CREATED_DATE]      DATETIME NULL,
    [CREATED_BY]        NVARCHAR(10) NULL,
    [CREATED_PRG_NM]    NVARCHAR(50) NULL,
    [UPDATED_DATE]      DATETIME NULL,
    [UPDATED_BY]        NVARCHAR(10) NULL,
    [UPDATED_PRG_NM]    NVARCHAR(50) NULL,
    [MODIFY_COUNT]      NUMERIC(10,0) NULL,

 CONSTRAINT [PK_T_PR_QT_H] PRIMARY KEY CLUSTERED
(
    [I_QT_NO] ASC
)WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    IGNORE_DUP_KEY = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON,
    OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
) ON [PRIMARY]
) ON [PRIMARY]
GO
