
SELECT 
	 [H].[I_SHIP_INST] AS [I_SHIP_ORDER_NO]
	,[H].[I_SHIP_INST_DATE] AS [I_SHIP_ORDER_DATE]
	,[IH].[I_INVOICE_NO]
	,[IH].[I_INVOICE_DATE]

	,[H].[I_CSCODE] AS [CORRESPONDENT]
	,[CS].[I_REMARK] AS [ATTN]
	,[H].[I_SHIPTO] AS [I_SHIP_TO]
FROM [T_PR_SHIP_INST_H] [H]
	LEFT JOIN [MS_CS] [CS]
		ON [CS].[I_CSCODE] = [H].[I_CSCODE]

	LEFT JOIN [T_PR_INVOICE_H] [IH]
		ON [IH].[I_SHIP_ORDER_NO] = [H].[I_SHIP_INST]

WHERE [H].[I_SHIP_INST] = /**%I_SHIP_ORDER_NO%**/'SI202512230023'