SELECT
    [MP].[I_ITEMCODE],
    [MP].[I_DESC],
    [MP].[I_COMMODITY],
    [MP].[I_THICK],
    [MP].[I_WIDTH],

    ([MP].[I_PROD_WGT] / 100.0) * (200.0 - [MP].[I_YIELD]) AS [I_PROD_WGT],
    ([MP].[I_RM_WGT]   / 100.0) * (200.0 - [MP].[I_YIELD]) AS [I_RM_WGT],
    ([MP].[I_LOSS_WGT] / 100.0) * (200.0 - [MP].[I_YIELD]) AS [I_LOSS_WGT],

    [MP].[I_PITCH],
    '' AS [MAT_COST],
    '' AS [SCRAP_COST],
    '' AS [MAT_AMOUNT],
    '' AS [SCRAP_AMOUNT],

    [MP].[I_FEE_PROCESS],
    [MP].[I_FEE_CUSTOM],
    [MP].[I_FEE_PACK],
    [MP].[I_FEE_EXPENSE],
    [MP].[I_FEE_DLY],

    COALESCE([MP].[I_FEE_PROCESS], 0)
  + COALESCE([MP].[I_FEE_CUSTOM], 0)
  + COALESCE([MP].[I_FEE_PACK], 0)
  + COALESCE([MP].[I_FEE_EXPENSE], 0)
  + COALESCE([MP].[I_FEE_DLY], 0) AS [MANAGEMENT_EXPENSE],

    ROUND(RAND(CHECKSUM(NEWID())) * 1350 + 150, 2) AS [TOTAL_PRICE],

    [MP].[I_QTPATTERN],
    [TQ].[I_QT_NO],
    [TQ].[I_CSCODE],
    [MP].[I_CSCOD],

    ROW_NUMBER() OVER (
        PARTITION BY [MP].[I_ITEMCODE]
        ORDER BY [MP].[I_ITEMCODE]
    ) AS [I_QT_LN]

FROM [MS_PRFG] AS [MP]
LEFT JOIN [T_PR_QT] AS [TQ]
    ON [TQ].[I_ITEMCODE] = [MP].[I_ITEMCODE]

WHERE 1 = 2