SELECT  
       sd.[I_SONO] AS [I_SONO]
       ,tq.[I_QT_NO]
       ,sd.[I_LNNO] AS [I_LNNO]
       ,sd.[I_SODATE] AS [I_SODATE]
       ,sd.[I_COMPCLS] AS [I_COMPCLS]
       ,sd.[I_CUSTOMER_PO] AS [I_CUSTOMER_PO]
       ,tq.[I_CSCODE]
       ,/**%I_NAME%**/'' AS [I_NAME]
       ,sd.[I_SHIPTO] AS [I_SHIPTO]
       ,sd.[I_BILLTO] AS [I_BILLTO]
       ,sd.[I_ENDUSER] AS [I_ENDUSER]
       ,sd.[I_CURRENCY] AS [I_CURRENCY]
       ,sd.[I_REM1] AS [I_REM1]
       ,tq.[I_QT_LN] AS [I_QT_LN]
       , /**%I_QT_NO%**/'' AS [QT_NO]
from [T_PR_SORD] sd
left join [T_PR_QT] tq ON sd.I_QT_NO = tq.[I_QT_NO]
left join [MS_CS] ms ON ms.[I_CSCODE] = sd.[I_CSODE]
