
SELECT 
     [GA_VOUCHERNO]
    ,[GA_INVOICENO]     
    ,[I_SONO]
    ,[I_QT_NO]
    ,[GA_RATETYPE]
    ,[GA_INPDATE]
    ,[GA_HEADER_DEPTCODE]
    ,[I_TYPE]
    ,[GA_DEPTCODE]
    ,[GA_ACCODE]
    ,[GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE]
    ,[GA_CORRESPTYPE]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_SC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_SC]
    ,[GA_TAXAMOUNT_FC]
    ,[GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE]
    ,[GA_POSTPADCOLOR]
    ,[GA_POSTPADTEXT]
FROM (
    SELECT 
         [IVD].[I_INVOICE_NO] AS [GA_VOUCHERNO]
        ,[IVD].[I_INVOICE_NO] AS [GA_INVOICENO]     
        ,[IVD].[I_SONO]
        ,[SD].[I_QT_NO]
        ,[QTH].[I_EXG_RATE_TYPE] AS [GA_RATETYPE]
        ,[IVH].[I_INVOICE_DATE] AS [GA_INPDATE]
        ,[IVD].[I_ITEMCODE]
        ,'AD' AS [GA_HEADER_DEPTCODE]
        ,[FG].[I_TYPE]
        ,[FG].[I_ITEM_GROUP]
        ,'102012' AS [GA_DEPTCODE]
        ,'40100050' AS [GA_ACCODE]
        ,'S999' AS [GA_HEADER_TAXABLECODE] 
        ,'1' AS [GA_TAXTYPE]
        ,'1' AS [GA_CORRESPTYPE]
        ,[IVD].[I_QTY]
        ,[IVD].[I_UNIT_PRICE]
        ,[IVD].[I_AMOUNT]
        ,ROUND(
            (ISNULL([QTD].[I_RM_AMT], 0) + ISNULL([QTD].[I_LOSS_AMT], 0)), 2
        ) * [IVD].[I_QTY] AS [ITEM_AMOUNT]
        ,0 AS [GA_TAXAMOUNT_FC]
        ,0 AS [GA_TAXAMOUNT_SC]
        ,'0' AS [GA_JOURNALTYPE]
        ,'' AS [GA_POSTPADCOLOR]
        ,'' AS [GA_POSTPADTEXT]

    FROM [dbo].[T_PR_INVOICE_D] [IVD]
        LEFT JOIN [T_PR_INVOICE_H] [IVH]
            ON [IVH].[I_INVOICE_NO] = [IVD].[I_INVOICE_NO] 
        LEFT JOIN [MS_PRFG] [FG]
            ON [FG].[I_ITEMCODE] = [IVD].[I_ITEMCODE]
        LEFT JOIN [T_PR_SORD_H] [SD]
            ON [SD].[I_SONO] = [IVD].[I_SONO]
        LEFT JOIN [T_PR_QT_H] [QTH]
            ON [QTH].[I_QT_NO] = [SD].[I_QT_NO]
        LEFT JOIN (
            SELECT [QD].[I_QT_NO]
                  ,[QD].[INTERNAL_NO]
                  ,[QD].[I_ITEMCODE]
                  ,[QD].[I_RM_AMT]
                  ,[QD].[I_LOSS_AMT]
                  ,[QD].[I_FEE_PROCESS]
                  ,[QD].[I_FEE_CUSTOM]
                  ,[QD].[I_FEE_PACK]
                  ,[QD].[I_FEE_EXPENSE]
                  ,[MP].[I_FEE_DLY]
                  ,[QD].[I_FEE_MGM]
            FROM [T_PR_QT_D] [QD]
                LEFT JOIN [MS_PRFG] AS [MP]
                    ON [MP].[I_ITEMCODE] = [QD].[I_ITEMCODE]
        ) AS [QTD]
            ON [QTD].[I_QT_NO] = [SD].[I_QT_NO]

            
    WHERE [IVH].[I_INVOICE_NO] = 'IV2602180018'
      AND [FG].[I_TYPE] = 1 
) AS [MAIN]
GROUP BY 
     [GA_VOUCHERNO], [GA_INVOICENO], [I_SONO], [I_QT_NO], [GA_RATETYPE], [GA_INPDATE]
    ,[GA_HEADER_DEPTCODE], [GA_DEPTCODE], [GA_ACCODE], [GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE], [GA_CORRESPTYPE], [GA_TAXAMOUNT_FC], [GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE], [GA_POSTPADCOLOR], [GA_POSTPADTEXT], [I_TYPE]

UNION ALL

SELECT 
     [GA_VOUCHERNO]
    ,[GA_INVOICENO]     
    ,[I_SONO]
    ,[I_QT_NO]
    ,[GA_RATETYPE]
    ,[GA_INPDATE]
    ,[GA_HEADER_DEPTCODE]
    ,[I_TYPE]
    ,[GA_DEPTCODE]
    ,[GA_ACCODE]
    ,[GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE]
    ,[GA_CORRESPTYPE]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_SC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_SC]
    ,[GA_TAXAMOUNT_FC]
    ,[GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE]
    ,[GA_POSTPADCOLOR]
    ,[GA_POSTPADTEXT]
FROM (
    SELECT 
         [IVD].[I_INVOICE_NO] AS [GA_VOUCHERNO]
        ,[IVD].[I_INVOICE_NO] AS [GA_INVOICENO]     
        ,[IVD].[I_SONO]
        ,[SD].[I_QT_NO]
        ,[QTH].[I_EXG_RATE_TYPE] AS [GA_RATETYPE]
        ,[IVH].[I_INVOICE_DATE] AS [GA_INPDATE]
        ,[IVD].[I_ITEMCODE]
        ,'AD' AS [GA_HEADER_DEPTCODE]
        ,[FG].[I_TYPE]
        ,[FG].[I_ITEM_GROUP]
        ,'102012' AS [GA_DEPTCODE]
        ,'40100055' AS [GA_ACCODE]
        ,'S999' AS [GA_HEADER_TAXABLECODE] 
        ,'1' AS [GA_TAXTYPE]
        ,'1' AS [GA_CORRESPTYPE]
        ,[IVD].[I_QTY]

        ,ROUND(
            (ISNULL([QTD].[I_FEE_PROCESS], 0) + 
             ISNULL([QTD].[I_FEE_CUSTOM], 0) + 
             ISNULL([QTD].[I_FEE_PACK], 0) + 
             ISNULL([QTD].[I_FEE_EXPENSE], 0) + 
             ISNULL([QTD].[I_FEE_DLY], 0) + 
             ISNULL([QTD].[I_FEE_MGM], 0)), 2
        ) * [IVD].[I_QTY] AS [ITEM_AMOUNT]
        ,0 AS [GA_TAXAMOUNT_FC]
        ,0 AS [GA_TAXAMOUNT_SC]
        ,'0' AS [GA_JOURNALTYPE]
        ,'' AS [GA_POSTPADCOLOR]
        ,'' AS [GA_POSTPADTEXT]

    FROM [dbo].[T_PR_INVOICE_D] [IVD]
        LEFT JOIN [T_PR_INVOICE_H] [IVH]
            ON [IVH].[I_INVOICE_NO] = [IVD].[I_INVOICE_NO] 
        LEFT JOIN [MS_PRFG] [FG]
            ON [FG].[I_ITEMCODE] = [IVD].[I_ITEMCODE]
        LEFT JOIN [T_PR_SORD_H] [SD]
            ON [SD].[I_SONO] = [IVD].[I_SONO]
        LEFT JOIN [T_PR_QT_H] [QTH]
            ON [QTH].[I_QT_NO] = [SD].[I_QT_NO]
        LEFT JOIN (
            SELECT [QD].[I_QT_NO]
                  ,[QD].[INTERNAL_NO]
                  ,[QD].[I_ITEMCODE]
                  ,[QD].[I_RM_AMT]
                  ,[QD].[I_LOSS_AMT]
                  ,[QD].[I_FEE_PROCESS]
                  ,[QD].[I_FEE_CUSTOM]
                  ,[QD].[I_FEE_PACK]
                  ,[QD].[I_FEE_EXPENSE]
                  ,[MP].[I_FEE_DLY]
                  ,[QD].[I_FEE_MGM]
            FROM [T_PR_QT_D] [QD]
                LEFT JOIN [MS_PRFG] AS [MP]
                    ON [MP].[I_ITEMCODE] = [QD].[I_ITEMCODE]
        ) AS [QTD]
            ON [QTD].[I_QT_NO] = [SD].[I_QT_NO]

            
    WHERE [IVH].[I_INVOICE_NO] = 'IV2602180018'
      AND [FG].[I_TYPE] = 1 
) AS [MAIN]
GROUP BY 
     [GA_VOUCHERNO], [GA_INVOICENO], [I_SONO], [I_QT_NO], [GA_RATETYPE], [GA_INPDATE]
    ,[GA_HEADER_DEPTCODE], [GA_DEPTCODE], [GA_ACCODE], [GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE], [GA_CORRESPTYPE], [GA_TAXAMOUNT_FC], [GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE], [GA_POSTPADCOLOR], [GA_POSTPADTEXT], [I_TYPE]

UNION ALL

SELECT 
     [GA_VOUCHERNO]
    ,[GA_INVOICENO]     
    ,[I_SONO]
    ,[I_QT_NO]
    ,[GA_RATETYPE]
    ,[GA_INPDATE]
    ,[GA_HEADER_DEPTCODE]
    ,[I_TYPE]
    ,[GA_DEPTCODE]
    ,[GA_ACCODE]
    ,[GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE]
    ,[GA_CORRESPTYPE]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_SC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_SC]
    ,[GA_TAXAMOUNT_FC]
    ,[GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE]
    ,[GA_POSTPADCOLOR]
    ,[GA_POSTPADTEXT]
FROM (
    SELECT 
         [IVD].[I_INVOICE_NO] AS [GA_VOUCHERNO]
        ,[IVD].[I_INVOICE_NO] AS [GA_INVOICENO]     
        ,[IVD].[I_SONO]
        ,[SD].[I_QT_NO]
        ,[QTH].[I_EXG_RATE_TYPE] AS [GA_RATETYPE]
        ,[IVH].[I_INVOICE_DATE] AS [GA_INPDATE]
        ,[IVD].[I_ITEMCODE]
        ,'AD' AS [GA_HEADER_DEPTCODE]
        ,[FG].[I_TYPE]
        ,[FG].[I_ITEM_GROUP]
        ,'102011' AS [GA_DEPTCODE]
        ,'40100050' AS [GA_ACCODE]
        ,'S999' AS [GA_HEADER_TAXABLECODE] 
        ,'1' AS [GA_TAXTYPE]
        ,'1' AS [GA_CORRESPTYPE]
        ,[IVD].[I_QTY]
        ,ROUND(
            (ISNULL([QTD].[I_RM_AMT], 0) + ISNULL([QTD].[I_LOSS_AMT], 0)), 2
        ) * [IVD].[I_QTY] AS [ITEM_AMOUNT]
        ,0 AS [GA_TAXAMOUNT_FC]
        ,0 AS [GA_TAXAMOUNT_SC]
        ,'0' AS [GA_JOURNALTYPE]
        ,'' AS [GA_POSTPADCOLOR]
        ,'' AS [GA_POSTPADTEXT]

    FROM [dbo].[T_PR_INVOICE_D] [IVD]
        LEFT JOIN [T_PR_INVOICE_H] [IVH]
            ON [IVH].[I_INVOICE_NO] = [IVD].[I_INVOICE_NO] 
        LEFT JOIN [MS_PRFG] [FG]
            ON [FG].[I_ITEMCODE] = [IVD].[I_ITEMCODE]
        LEFT JOIN [T_PR_SORD_H] [SD]
            ON [SD].[I_SONO] = [IVD].[I_SONO]
        LEFT JOIN [T_PR_QT_H] [QTH]
            ON [QTH].[I_QT_NO] = [SD].[I_QT_NO]
        LEFT JOIN (
            SELECT [QD].[I_QT_NO]
                  ,[QD].[INTERNAL_NO]
                  ,[QD].[I_ITEMCODE]
                  ,[QD].[I_RM_AMT]
                  ,[QD].[I_LOSS_AMT]
                  ,[QD].[I_FEE_PROCESS]
                  ,[QD].[I_FEE_CUSTOM]
                  ,[QD].[I_FEE_PACK]
                  ,[QD].[I_FEE_EXPENSE]
                  ,[MP].[I_FEE_DLY]
                  ,[QD].[I_FEE_MGM]
            FROM [T_PR_QT_D] [QD]
                LEFT JOIN [MS_PRFG] AS [MP]
                    ON [MP].[I_ITEMCODE] = [QD].[I_ITEMCODE]
        ) AS [QTD]
            ON [QTD].[I_QT_NO] = [SD].[I_QT_NO]

            
    WHERE [IVH].[I_INVOICE_NO] = 'IV2602180018'
      AND ([FG].[I_TYPE] <> 1 OR [FG].[I_TYPE] IS NULL)
) AS [MAIN]
GROUP BY 
     [GA_VOUCHERNO], [GA_INVOICENO], [I_SONO], [I_QT_NO], [GA_RATETYPE], [GA_INPDATE]
    ,[GA_HEADER_DEPTCODE], [GA_DEPTCODE], [GA_ACCODE], [GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE], [GA_CORRESPTYPE], [GA_TAXAMOUNT_FC], [GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE], [GA_POSTPADCOLOR], [GA_POSTPADTEXT], [I_TYPE]

UNION ALL

SELECT 
     [GA_VOUCHERNO]
    ,[GA_INVOICENO]     
    ,[I_SONO]
    ,[I_QT_NO]
    ,[GA_RATETYPE]
    ,[GA_INPDATE]
    ,[GA_HEADER_DEPTCODE]
    ,[I_TYPE]
    ,[GA_DEPTCODE]
    ,[GA_ACCODE]
    ,[GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE]
    ,[GA_CORRESPTYPE]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_INPAMOUNT_SC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_FC]
    ,SUM([ITEM_AMOUNT]) AS [GA_TAXABLEAMOUNT_SC]
    ,[GA_TAXAMOUNT_FC]
    ,[GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE]
    ,[GA_POSTPADCOLOR]
    ,[GA_POSTPADTEXT]
FROM (
    SELECT 
         [IVD].[I_INVOICE_NO] AS [GA_VOUCHERNO]
        ,[IVD].[I_INVOICE_NO] AS [GA_INVOICENO]     
        ,[IVD].[I_SONO]
        ,[SD].[I_QT_NO]
        ,[QTH].[I_EXG_RATE_TYPE] AS [GA_RATETYPE]
        ,[IVH].[I_INVOICE_DATE] AS [GA_INPDATE]
        ,[IVD].[I_ITEMCODE]
        ,'AD' AS [GA_HEADER_DEPTCODE]
        ,[FG].[I_TYPE]
        ,[FG].[I_ITEM_GROUP]
        ,'102011' AS [GA_DEPTCODE]
        ,'40100055' AS [GA_ACCODE]
        ,'S999' AS [GA_HEADER_TAXABLECODE] 
        ,'1' AS [GA_TAXTYPE]
        ,'1' AS [GA_CORRESPTYPE]
        ,[IVD].[I_QTY]

        ,ROUND(
            (ISNULL([QTD].[I_FEE_PROCESS], 0) + 
             ISNULL([QTD].[I_FEE_CUSTOM], 0) + 
             ISNULL([QTD].[I_FEE_PACK], 0) + 
             ISNULL([QTD].[I_FEE_EXPENSE], 0) + 
             ISNULL([QTD].[I_FEE_DLY], 0) + 
             ISNULL([QTD].[I_FEE_MGM], 0)), 2
        ) * [IVD].[I_QTY] AS [ITEM_AMOUNT]
        ,0 AS [GA_TAXAMOUNT_FC]
        ,0 AS [GA_TAXAMOUNT_SC]
        ,'0' AS [GA_JOURNALTYPE]
        ,'' AS [GA_POSTPADCOLOR]
        ,'' AS [GA_POSTPADTEXT]

    FROM [dbo].[T_PR_INVOICE_D] [IVD]
        LEFT JOIN [T_PR_INVOICE_H] [IVH]
            ON [IVH].[I_INVOICE_NO] = [IVD].[I_INVOICE_NO] 
        LEFT JOIN [MS_PRFG] [FG]
            ON [FG].[I_ITEMCODE] = [IVD].[I_ITEMCODE]
        LEFT JOIN [T_PR_SORD_H] [SD]
            ON [SD].[I_SONO] = [IVD].[I_SONO]
        LEFT JOIN [T_PR_QT_H] [QTH]
            ON [QTH].[I_QT_NO] = [SD].[I_QT_NO]
        LEFT JOIN (
            SELECT [QD].[I_QT_NO]
                  ,[QD].[INTERNAL_NO]
                  ,[QD].[I_ITEMCODE]
                  ,[QD].[I_RM_AMT]
                  ,[QD].[I_LOSS_AMT]
                  ,[QD].[I_FEE_PROCESS]
                  ,[QD].[I_FEE_CUSTOM]
                  ,[QD].[I_FEE_PACK]
                  ,[QD].[I_FEE_EXPENSE]
                  ,[MP].[I_FEE_DLY]
                  ,[QD].[I_FEE_MGM]
            FROM [T_PR_QT_D] [QD]
                LEFT JOIN [MS_PRFG] AS [MP]
                    ON [MP].[I_ITEMCODE] = [QD].[I_ITEMCODE]
        ) AS [QTD]
            ON [QTD].[I_QT_NO] = [SD].[I_QT_NO]

            
    WHERE [IVH].[I_INVOICE_NO] = 'IV2602180018'
      AND ([FG].[I_TYPE] <> 1)
) AS [MAIN]
GROUP BY 
     [GA_VOUCHERNO], [GA_INVOICENO], [I_SONO], [I_QT_NO], [GA_RATETYPE], [GA_INPDATE]
    ,[GA_HEADER_DEPTCODE], [GA_DEPTCODE], [GA_ACCODE], [GA_HEADER_TAXABLECODE]
    ,[GA_TAXTYPE], [GA_CORRESPTYPE], [GA_TAXAMOUNT_FC], [GA_TAXAMOUNT_SC]
    ,[GA_JOURNALTYPE], [GA_POSTPADCOLOR], [GA_POSTPADTEXT], [I_TYPE]
ORDER BY [GA_ACCODE], [GA_DEPTCODE]